name: Build Blender addons

on:
  push:
    tags:
      - "*"

jobs:
  windows-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        python-version: ['3.7', '3.10.9']

    steps:
    - uses: actions/checkout@v2
    - uses: suisei-cn/actions-download-file@v1.6.0
      id: download-swigwin-zip  # Remember to give an ID if you need the output filename
      name: Download swigwin-4.2.0.zip
      with:
        url: "https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.2.0/swigwin-4.2.0.zip"
        target: "C:\\swig"
    - name: Extract swigwin-4.2.0.zip
      run: |
        cd C:\swig
        7z x ${{ steps.download-swigwin-zip.outputs.filename }}
    - name: Verify SWIG
      run: C:\swig\swigwin-4.2.0\swig.exe -version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build gsutil using distutils
      run: |
        cd ${{github.workspace}}\PS2\Common\gsutil
        C:\swig\swigwin-4.2.0\swig.exe -python -c++ gsutil.i
        python setup.py build_ext --inplace
        dir
    - name: Zip compiled extension
      run: |
        cd "${{github.workspace}}\PS2\Common\gsutil"
        7z a "${{github.workspace}}\gsutil-win64-${{ matrix.python-version }}-build.zip" gsutil.py *.pyd
    - name: Upload compiled extension
      uses: actions/upload-artifact@v1
      with:
        name: "win64-${{ matrix.python-version }}"
        path: "${{github.workspace}}\\gsutil-win64-${{ matrix.python-version }}-build.zip"

  create-release:
    needs: [windows-build]
    runs-on: "ubuntu-22.04"
    steps:
    - name: Download Windows Python 3.7 build
      uses: actions/download-artifact@v1
      with:
        name: "win64-3.7"
    - name: Download Windows Python 3.10.9 build
      uses: actions/download-artifact@v1
      with:
        name: "win64-3.10.9"
    - name: Collate build artefacts in gsutil
      run: |
        move win64-3.7/gsutil-win64-3.7-build.zip ${{github.workspace}}\PS2\Common\gsutil
        move win64-3.10.9/gsutil-win64-3.10.9-build.zip ${{github.workspace}}\PS2\Common\gsutil
        cd "${{github.workspace}}\PS2\Common\gsutil"
        7z x gsutil-win64-3.7-build.zip
        7z x gsutil-win64-3.10.9-build.zip
        del *.zip
    - name: Construct addons
      run: |
        cd "${{github.workspace}}\PS2\Silent Hill 2+3\Blender\addons"
        robocopy io_sh2_sh3 C:\io_sh2_sh3 /e
        cd C:\
        7z a io_sh2_sh3.zip io_sh2_sh3
        move io_sh2_sh3.zip "${{github.workspace}}\io_sh2_sh3.zip"
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: "${{github.workspace}}\\io_sh2_sh3.zip"
        fail_on_unmatched_files: true
