name: Build Blender addons

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        python-version: ['3.10.9']

    steps:
    - uses: actions/checkout@v2
    - uses: suisei-cn/actions-download-file@v1.6.0
      id: download-swigwin-zip  # Remember to give an ID if you need the output filename
      name: Download swigwin-4.2.0.zip
      with:
        url: "https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.2.0/swigwin-4.2.0.zip"
        target: "C:\\swig"
    - name: Extract swigwin-4.2.0.zip
      run: |
        cd C:\swig
        7z x ${{ steps.download-swigwin-zip.outputs.filename }}
    - name: Verify SWIG
      run: C:\swig\swigwin-4.2.0\swig.exe -version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build gsutil using distutils
      run: |
        cd ${{github.workspace}}\PS2\Common\gsutil
        C:\swig\swigwin-4.2.0\swig.exe -python -c++ gsutil.i
        python setup.py build_ext --inplace
        dir
    - name: Construct addons
      run: |
        cd ${{github.workspace}}\PS2\Common\gsutil
        7z a ..\readutil\io_sh2_sh3.zip .\*
        cd ${{github.workspace}}\PS2\Common\readutil
        7z a io_sh2_sh3.zip .\readutil.py
        move io_sh2_sh3.zip "${{github.workspace}}\PS2\Silent Hill 2+3\Blender\addons\io_sh2_sh3\io_sh2_sh3.zip"
        cd "${{github.workspace}}\PS2\Silent Hill 2+3\Blender\addons\io_sh2_sh3"
        7z a io_sh2_sh3.zip __init__.py export_pack.py import_anm.py import_dds.py import_map.py import_mdl.py import_pack.py vu.py
        move io_sh2_sh3.zip "${{github.workspace}}\io_sh2_sh3_py${{ matrix.python-version }}_win64.zip"
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: "${{github.workspace}}\io_sh2_sh3_py${{ matrix.python-version }}_win64.zip"
        fail_on_unmatched_files: true
        prerelease: true
